server:
  port: 9094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookserviceapp
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: BOOK-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


