spring:
  application:
    name: API-Gateway


  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
        - id: LIBRARY-SERVICE
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/library/**
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/book/**

server:
  port: 9096
eureka:
  instance:
    hostname: localhost


